version: '3.8'

services:
  benchmark-server:
    image: amazonlinux:2023
    container_name: benchmark-amazon-linux
    working_dir: /workspace
    volumes:
      - .:/workspace:rw
    ports:
      - "3001-3009:3001-3009"
    environment:
      - TERM=xterm-256color
    stdin_open: true
    tty: true
    command: /bin/bash