[workspace]
members = [
    "actix",
    "axum",
    "rocket",
]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1.40", features = ["full"] }
dotenv = "0.15"
reqwest = { version = "0.12", features = ["stream"] }
futures = "0.3"
bytes = "1.7"